### ISSUE TITLE
add a contributors section that auto displays the images and names of all the contributors

### ISSUE THREAD

**Issue by samanyougarg** [gita/bhagavad-gita-api#22]

**Comment by NIKU-SINGH** [comment]
Hey, I would Like to work on this issue.
As I understand I have to create a Contributors.MD for this repo? Then it would be great if you could tell me where can I get names and Github ids so that I can start working.

**Comment by samanyougarg** [comment]
You can use this: https://github.com/all-contributors/all-contributors

**Comment by samanyougarg** [comment]
@all-contributors please add @Amritpal2001 for code

**Comment by samanyougarg** [comment]
@all-contributors please add @akshatj2209 for code

**Comment by samanyougarg** [comment]
@all-contributors please add @aahnik for code

**Comment by samanyougarg** [comment]
@all-contributors please add @akshatj2209 for code

**Comment by samanyougarg** [comment]
@all-contributors please add @NIKU-SINGH for code

**Comment by samanyougarg** [comment]
Implemented in #36

**Comment by samanyougarg** [comment]
@all-contributors please add @NIKU-SINGH for code
