### ISSUE TITLE
Error while running with sqlite

### ISSUE THREAD

**Issue by sanujsood** [gita/bhagavad-gita-api#25]
![image](https://user-images.githubusercontent.com/67072668/124656475-e316b200-debe-11eb-93cd-710db4dd21fc.png)

we need to add this arguement automatically when using sqlite 

`connect_args={"check_same_thread": False}`

**Comment by samanyougarg** [comment]
@all-contributors please add @sanujsood for code

**Comment by samanyougarg** [comment]
Solved.

**Comment by Gupta-Anubhav12** [comment]
The code remains unchanged reflecting the same error , Issue was closed by mistake reckon,
Reopening for operation with sqlite , check same thread = false parameter Issue 
Please take up on this

**Comment by Gupta-Anubhav12** [comment]
My Bad , I didn't see the edit in config.py 
sorry
Solved
