### ISSUE TITLE
Misc Todo

### ISSUE THREAD

**Issue by aahnik** [gita/bhagavad-gita-api#5]
Once PR #3  is merged, I will start working on these

- [ ] #14
- [ ] #15
- [ ] #16
- [x] reference once and update json data (the scripts that create references are too slow (why ?)) related to #11 
- [x] #6
- [x] #7
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21

**Comment by samanyougarg** [comment]
For the `/` route, we will be creating a tiny frontend, where the users who are interested in trying out the API can fill in a form to request an API key.

**Comment by samanyougarg** [comment]
All of the points you mentioned are great points and will massively help in improving the system 🤩
