### ISSUE TITLE
Add Redis to docker-compose files

### ISSUE THREAD

**Issue by samanyougarg** [gita/bhagavad-gita-api#58]
We need to add Redis to the docker-compose files so that celery can make use of them for **verse of the day** feature.

**Comment by SanthoshS20** [comment]
@samanyougarg Can I contribute to this Issue?

**Comment by samanyougarg** [comment]
@SanthoshS20 Sure, assigning to you.

**Comment by SanthoshS20** [comment]
@samanyougarg 

Facing this issue while raising PR

remote: Permission to gita/bhagavad-gita-api.git denied to SanthoshS20.
fatal: unable to access 'https://github.com/gita/bhagavad-gita-api.git/': The requested URL returned error: 403

**Comment by samanyougarg** [comment]
Please read the [contributing guide](https://github.com/gita/bhagavad-gita-api/blob/main/.github/CONTRIBUTING.md). You need to fork the repo, make changes in the forked one on a new branch and then submit a PR for this repo.
