### ISSUE TITLE
think about using https://github.com/tiangolo/pydantic-sqlalchemy

### ISSUE THREAD

**Issue by aahnik** [gita/bhagavad-gita-api#6]
we are manually creating the pydantic schemas. but the can be auto-generated from the sqlalchemy model

**Comment by samanyougarg** [comment]
For some of the models, the corresponding schema consists only of a subset of the fields present in the model.

Example:
For the `GitaCommentary` schema, we are returning just 3 out of 8 fields present in the corresponding model.

Does this library have an option to specify which fields are needed?

**Comment by aahnik** [comment]
the library is still experimental as mentioned in its readme.

besides the readme, I could not find any other docs for the lib.

> Does this library have an option to specify which fields are needed?

I think this is not possible. 

So, I think let's stick with what code we currently have.
