### ISSUE TITLE
Add Sanskrit Recitations 

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/bhagavad-gita-api#64]
Adding Sanskrit recitations from a reliable source to backend, making the field for that and deciding a cdn service for audio files, 
as of now we can add the audio files along with JSON stored in https://github.com/gita/gita repo and it would work

**Comment by Gupta-Anubhav12** [comment]
The recitations have been merged to json repo, 
now the API has to be modified for sending out audio from endpoints

**Comment by Srishtikumari2002** [comment]
created resolver function for adding Sanskrit recitation url  to the API and have made necessary changes in following files
* .env.example - added recitation_url host
* api/api_v2/endpoints/gita.py - modified resolver function to include recitation url
* models/schemas.py - added the recitation url field
