### ISSUE TITLE
Create an index page with a readme, API registration form and links to docs & repo

### ISSUE THREAD

**Issue by samanyougarg** [gita/bhagavad-gita-api#7]
Currently, the `/` route returns 404. 

Instead, we should create an index page with a readme, API registration form, and links to docs & repo.

For simplicity, let's just use Jinja2 along with Bootstrap instead of creating a SPA using react/vue.

**Comment by irsayvid** [comment]
I would like to work on this issue. I'm new to Jinja so it would take some time. If that's fine, can you please assign me this issue?

**Comment by Gupta-Anubhav12** [comment]
Hii 
We already use the for this so we can skip this issue.
