### ISSUE TITLE
Set up a CI/CD pipeline on Github actions that deploys the API to DO/AWS

### ISSUE THREAD

**Issue by samanyougarg** [gita/bhagavad-gita-api#9]

**Comment by aahnik** [comment]
hi @samanyougarg  will you be using DO for production? then please use my link  (https://m.do.co/c/98b7250551480) to sign up. (you get 100$, and I get 25$, thus I sustain the costs of my experimentation. ) 

for our users, then can use the DO app platform to deploy any docker image.
once we publish our docker image, we can write the guide, of steps to follow to deploy to DO. (Fully from browser, no terminal needed.)

**Comment by samanyougarg** [comment]
We plan to use one of DO/AWS for now since we already have an account there. (Not sure if I can use your coupon since the account is quite old)

**Comment by samanyougarg** [comment]
Potential solutions:

1. DigitalOcean App Platform
2. Dokku on DigitalOcean Droplets
3. AWS ElasticBeanstalk
4. AWS ECR/ECS with docker

**Comment by samanyougarg** [comment]
Assigned to @sreevardhanreddi.

**Comment by samanyougarg** [comment]
@all-contributors please add @sreevardhanreddi for code, infra

**Comment by samanyougarg** [comment]
Implemented in #40
